# Generated by Django 6.0.1 on 2026-01-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sugar_free', 'Без сахара'), ('vegan', 'Для веганов'), ('vegetarian', 'Для вегетарианцев'), ('lactose_free', 'Без лактозы'), ('gluten_free', 'Без глютена')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Краткое описание диеты')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='diets',
            field=models.ManyToManyField(blank=True, to='app.diet'),
        ),
    ]
